### PR TITLE
Remove measurement unit type as parameter, since it can only be KWh.

### PR DESCRIPTION
**Pull request by kft**

### CODE REVIEW

**Comment by erduna** [comment]
Are we sure about this?:
image
image

**Comment by erduna** [comment]
We can see the default type is kWh for almost all mp types (but not all). We also see available unit types mentioned. Maybe kWh is the only unit actually used, but does that exclude the others?

**Comment by kft** [comment]
> We can see the default type is kWh for almost all mp types (but not all). We also see available unit types mentioned. Maybe kWh is the only unit actually used, but does that exclude the others?

This is only for Consumption metering points. Not all MP-types

**Review by Korgath — APPROVED** [review]

**Comment by erduna** [comment]
> 
> 
> > We can see the default type is kWh for almost all mp types (but not all). We also see available unit types mentioned. Maybe kWh is the only unit actually used, but does that exclude the others?
> 
> This is only for Consumption metering points. Not all MP-types

Ok. Corroborated here:
image

**Review by erduna — APPROVED** [review]

**Pull request merged**
